// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhgbxkzutnzissjqqbum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZ2J4a3p1dG56aXNzanFxYnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU4OTAzMjQsImV4cCI6MjEwMTQ2NjMyNH0.Tt5x6Jwmpn4eWsaQe-eWxC6jVeIBzLPBJ3gs0p34dZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});